# -*- coding: utf-8 -*-
{
    'name': 'Atharva Theme Base',
    'category': 'Base',
    'summary': 'Base module for Atharva E-commerce themes',
    'version': '3.0',
    'license': 'OPL-1',
    'author': 'Atharva System',
	'support': 'support@atharvasystem.com',
    'website' : 'https://www.atharvasystem.com',
	'description': """Base module for Atharva E-commerce themes""",
    'depends': [
        'website_sale',
        'website_blog',
        'website_sale_wishlist',
        'website_sale_comparison',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/assets.xml',
        'views/templates.xml',
        'views/product_slider_layout_view.xml',
        'views/product_brand_view.xml',
        'views/megamenu_views.xml',
        'views/megamenu_template.xml',
        'views/faqs_views.xml',
        'views/product_varient_slider_layout_view.xml',
        'views/category_slider_layout_view.xml',
        'views/product_sticker_view.xml',
        'views/product_label_view.xml',
        'views/brand_slider_layout_view.xml',
        'views/quick_cart_template.xml',
        'views/quick_load_product_template.xml',
        'views/product_sticker_template.xml',
        'views/product_brand_template.xml',
        'views/blog_configure_view.xml',
        'views/product_tab.xml',
        'views/cart.xml',
        'views/pwa_view.xml',
        'views/pwa_template.xml',
        'views/product_tags_view.xml',
        'views/quick_load_views.xml'
    ],
    'demo':['demo/demo.xml'],
	'price': 4.00,
    'currency': 'EUR',
    'images': ['static/description/as-theme-base.png'],
    'installable': True,
    'application': True
}
