from . import product_product
from . import account_journal
from . import sale_order
from . import account_tax
from . import account_invoice_tax
from . import account_move
from . import account_move_line
from . import account_payment
from . import stock_picking
from . import stock_move