# -*- coding: utf-8 -*-
{
    'name': 'Theme Alan',
    'category': 'Theme/eCommerce',
    'summary': 'All in One Fully Responsive and Pixel Perfect Odoo Theme for all eCommerce Businesses like Fashion, Electronics, Jwellery, Beauty, Furniture, Sports etc.',
    'version': '2.15',
    'license': 'OPL-1',
    'author': 'Atharva System',
    'support': 'support@atharvasystem.com',
    'website' : 'https://www.atharvasystem.com',
    'description': """
    Theme Alan is one of the most powerful, amazing and flexible theme on Odoo store.
    Multipurpose Premium Responsive Odoo Themes - Fashion, Furniture, Sports, Jewellery, Corporate.
Creative theme,
Ecommerce theme,
Entertainment theme,
Personal theme,
Services theme,
Technology theme,
Business theme,
Multipurpose odoo theme,
Multi-purpose theme,
Theme Alan,
Odoo new themes,
Alan Theme,
Bootstrap4 odoo themes,
eCommerce Businesses,
Odoo RTL Theme,
Right to left theme, Odoo Arabic (Right to Left) - RTL, Odoo RTL Direction, Right to left support in Odoo
best odoo themes, meilleurs themes odoo, afdal almawadie odoo, tema odoo terbaik, beste odoo-themen, krashchi temy ooo, en iyi odoo temalari,
cele mai bune teme odoo
       """,
    'depends': [
        'atharva_theme_base'
    ],
    'data':[
        'views/assets.xml',
        'views/product_quick_view_template.xml',
        'views/brand_page_template.xml',
        'views/product_rating.xml',
        'views/product_label_template.xml',
        'views/snippets/s_deal_of_the_day1.xml',
        'views/snippets/s_deal_of_the_day2.xml',
        'views/snippets/s_deal_of_the_day3.xml',
        'views/snippets/s_alan_snippet_builder.xml',
        'views/snippets/s_product_slider.xml',
        'views/snippets/s_product_var_slider.xml',
        'views/snippets/s_latest_product_slider.xml',
        'views/snippets/s_category_product_slider.xml',
        'views/snippets/s_brand_slider.xml',
        'views/snippets/s_best_seller_product.xml',
        'views/snippets/s_brand_product_slider.xml',
        'views/snippets/s_category_slider.xml',
        'views/snippets/s_faq_snippet.xml',
        'views/snippets/s_offer_timer.xml',
        'views/snippets/s_blog_slider.xml',
        'views/snippets/s_product_banner_slider.xml',
        'views/snippets/snippets.xml',
        'views/snippets/snippet_header.xml',
        'views/snippets/snippet_footer.xml',
        'views/snippets/snippet_shop.xml',
        'views/snippets/s_img_hotspot.xml',
        'views/product_slider_template.xml',
        'views/varient_product_slider_template.xml',
        'views/common_slider_layout_template.xml',
        'views/brand_slider_layout_template.xml',
        'views/category_slider_layout_template.xml',
        'views/product_share.xml',
        'views/custom_header.xml',
        'views/custom_footer.xml',
        'views/custom_shop.xml',
        'views/product_detail_template.xml',
        'views/shop.xml',
        'views/custom_button.xml',
        'views/snippets/snippet_button.xml',
        'views/custom_image_zoom.xml',
        'views/product_banner_template.xml',
        'views/product_banner_slider_view.xml',
        'views/login_popup.xml',
        'views/quick_alternative.xml',
        'views/multi_image_slider.xml',
        'views/quick_add_to_cart.xml',
        'data/slider_layout_data.xml',
        'data/varient_slider_layout_data.xml',
        'data/common_slider_layout_data.xml',
        'data/brand_slider_layout_data.xml',
        'data/category_slider_layout_data.xml',
    ],
    'demo': [
        'demo/demo.xml'
    ],
    'live_test_url': 'https://alan-v14.atharvasystem.com',
    'images': ['static/description/alan_banner.png','static/description/alan_banner_screenshot.gif'],
    'price': 195.00,
    'application': False,
}
